### ISSUE TITLE
DistutilsOptionError on pip install

### ISSUE THREAD

**Issue by Dissonant-Tech** [terraform-aws-modules/terraform-aws-lambda#107]
I'm trying to use the following code:

```terraform
module "lambda_function" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = "${var.prefix}-example"
  handler       = "lambda_function.lambda_handler"
  runtime       = "python3.6"

  source_path = "../../lambda_src_dir"

  vpc_security_group_ids = var.lambda-security-groups
  vpc_subnet_ids         = var.lambda-subnet-ids

  tags = {
    Name = "${var.prefix}-jwt"
  }
}
```

But all runs are currently failing with the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
zip: Error during zip archive creation
Traceback (most recent call last):
  File ".terraform/modules/api-gateway.lambda_function/package.py", line 1137, in build_command
    bpm.execute(build_plan, zs, query)
  File ".terraform/modules/api-gateway.lambda_function/package.py", line 767, in execute
    with install_pip_requirements(query, pip_requirements) as rd:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File ".terraform/modules/api-gateway.lambda_function/package.py", line 903, in install_pip_requirements
    check_call(pip_command, env=subproc_env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3.6', '-m', 'pip', 'install', '--no-compile', '--prefix=', '--target=.', '--requirement=requirements.txt']' returned non-zero exit status 2.
```

**Comment by ahlinc** [comment]
It seems  somewhere in your system `--user` option is configured. You need to turn it off. Try to use a [`pip config list`](https://pip.pypa.io/en/stable/reference/pip_config/#cmdoption-user) command to figure out does it is.
