### ISSUE TITLE
Python packaging fails in Terraform Cloud

### ISSUE THREAD

**Issue by egalev** [terraform-aws-modules/terraform-aws-lambda#216]
## Description

When using Terraform Cloud Run environment, apply fails at the `module.coreapi_lambda.null_resource.archive[0]` resource, with the following trace:

```
Executing: ["python3" ".terraform/modules/coreapi_lambda/package.py" "build" "--timestamp" "1634735951309778000" "builds/4bb5e227c44fc37defeda68f5b9905bb0c3dcf3f02b0f453f3cfddea6d357d47.plan.json"]
  zip: creating 'builds/4bb5e227c44fc37defeda68f5b9905bb0c3dcf3f02b0f453f3cfddea6d357d47.zip' archive
  Installing python requirements: ../core/requirements.txt
  > mktemp -d terraform-aws-lambda-XXXXXXXX # /tmp/terraform-aws-lambda-ns3rqjt3
  > cd /tmp/terraform-aws-lambda-ns3rqjt3
  > python3.7 -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt
  zip: Error during zip archive creation
  Traceback (most recent call last):
    File ".terraform/modules/coreapi_lambda/package.py", line 924, in install_pip_requirements
      check_call(pip_command, env=subproc_env)
    File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/usr/lib/python3.6/subprocess.py", line 287, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'python3.7': 'python3.7'
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File ".terraform/modules/coreapi_lambda/package.py", line 1158, in build_command
      bpm.execute(build_plan, zs, query)
    File ".terraform/modules/coreapi_lambda/package.py", line 788, in execute
      with install_pip_requirements(query, pip_requirements) as rd:
    File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
      return next(self.gen)
    File ".terraform/modules/coreapi_lambda/package.py", line 930, in install_pip_requirements
      ) from e
  RuntimeError: Python interpreter version equal to defined lambda runtime (python3.7) should be available in system PATH
```

## ⚠️ Note

**Local apply as described below 👇 succeeded.**

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ terraform-aws-modules/lambda/aws 2.22.0 for coreapi_lambda

## Reproduction

Using Terraform Cloud Run in a Workspace fails with the above trace.

Using a local state, with or without a workspace, succeeds without the above issue.
### Code Snippet to Reproduce

This is my configuration (separate files, merged here for convenience):
```
provider "aws" {
  region = var.region
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.63.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "3.0.0"
    }
  }

  required_version = "~> 1.0"
}

module "coreapi_lambda" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = var.coreapi_function_name
  handler       = "src.main.lambda_handler"
  runtime       = var.coreapi_lambda_runtime

  source_path = "../core"

  vpc_subnet_ids = [aws_default_subnet.default_az1.id]
  vpc_security_group_ids = [aws_security_group.allow_nfs_traffic_to_efs.id]
  attach_network_policy = true

  tags = {
    Name = var.coreapi_function_name
  }
}

variable "region" {
  description = "AWS region"
  default     = "us-east-1"
}

variable "coreapi_function_name" {
  default = "coreapi_backend"
}

variable "coreapi_lambda_runtime" {
  default = "python3.7"
}
```
## Expected behavior
When running locally, the command succeeds:
```
module.coreapi_lambda.null_resource.archive[0] (local-exec): Executing: ["python.exe" ".terraform/modules/coreapi_lambda/package.py" "build" "--timestamp" "1634737191093293000" "builds\\69eeba9634537
56ac782588e0a5022290d580d13ddb53793e0ab2222dfe2bf36.plan.json"]
module.coreapi_lambda.null_resource.archive[0] (local-exec): zip: creating 'builds\69eeba963453756ac782588e0a5022290d580d13ddb53793e0ab2222dfe2bf36.zip' archive
module.coreapi_lambda.null_resource.archive[0] (local-exec): Installing python requirements: ../core\requirements.txt
module.coreapi_lambda.null_resource.archive[0] (local-exec): > mktemp -d terraform-aws-lambda-XXXXXXXX # 'C:\Users\Yigal\AppData\Local\Temp\terraform-aws-lambda-rv4pzna0'
module.coreapi_lambda.null_resource.archive[0] (local-exec): > cd 'C:\Users\Yigal\AppData\Local\Temp\terraform-aws-lambda-rv4pzna0'
module.coreapi_lambda.null_resource.archive[0] (local-exec): > python.exe -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt
module.coreapi_lambda.null_resource.archive[0] (local-exec): Collecting aws-lambda-wsgi==0.0.6
module.coreapi_lambda.null_resource.archive[0] (local-exec):   Using cached aws_lambda_wsgi-0.0.6-py3-none-any.whl (3.8 kB)
module.coreapi_lambda.null_resource.archive[0] (local-exec): Collecting connexion==2.9.0
module.coreapi_lambda.null_resource.archive[0] (local-exec):   Using cached connexion-2.9.0-py2.py3-none-any.whl (84 kB)
module.coreapi_lambda.null_resource.archive[0] (local-exec): Collecting flask<2,>=1.0.4
module.coreapi_lambda.null_resource.archive[0] (local-exec):   Using cached Flask-1.1.4-py2.py3-none-any.whl (94 kB)
module.coreapi_lambda.null_resource.archive[0] (local-exec): Collecting openapi-spec-validator<0.4,>=0.2.4
module.coreapi_lambda.null_resource.archive[0] (local-exec):   Using cached openapi_spec_validator-0.3.1-py3-none-any.whl (32 kB)
module.coreapi_lambda.null_resource.archive[0] (local-exec): Collecting inflection<0.6,>=0.3.1
...
Package installation continues
...
module.coreapi_lambda.null_resource.archive[0] (local-exec): Created: 'builds\69eeba963453756ac782588e0a5022290d580d13ddb53793e0ab2222dfe2bf36.zip'
module.coreapi_lambda.null_resource.archive[0]: Creation complete after 41s [id=7651629136115322200]
```

## Actual behavior
The Cloud Run environment fails when creating the python deployment package.

**Comment by stevewillard** [comment]
Do you know if it's possible to install a later version of Python on the Terraform Cloud machines?

**Comment by stopmachine** [comment]
> Do you know if it's possible to install a later version of Python on the Terraform Cloud machines?

Hashicorp don't seem to be interested too much in the build process of Lambda packages in Terraform Cloud, they expect you to create your own Runners, or use a different tool for Lambda packaging.

**Comment by antonbabenko** [comment]
@stevewillard There is a note in README - https://github.com/terraform-aws-modules/terraform-aws-lambda#-terraform-cicd
