### ISSUE TITLE
The module should package poetry dependencies

### ISSUE THREAD

**Issue by aminclip** [terraform-aws-modules/terraform-aws-lambda#417]
## Description

We are encountering an issue when trying to package Poetry dependencies with the following error: No such file or directory: 'poetry config --no-interaction virtualenvs.create true'. We are trying to package the dependencies using Poetry but the process is failing.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 4.9.0
- Terraform version: v1.3.6
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```
## Reproduction Code [Required]
1. Create a Poetry project in your module with .toml and .lock files under `PROJECT/code` directory.
2. Try to run `terraform apply`

Are you using workspaces? 
No.

Have you cleared the local cache (see Notice section above)? 
Yes.

## Expected behavior
The expected behavior is that the dependencies should be packaged successfully without any errors.

## Actual behavior
The actual behavior is that we are encountering the error message No such file or directory: `poetry config --no-interaction virtualenvs.create true` when trying to package the dependencies.

### Terminal Output Screenshot(s)

```
│ Installing python dependencies with poetry & pip: .terraform/modules/this/code/poetry.lock
│ > mktemp -d terraform-aws-lambda-XXXXXXXX # /var/folders/4b/sgc_nhbs6s3frndkq1c_nqwm0000gp/T/terraform-aws-lambda-p8sv_58c
│ Using poetry lock file: .terraform/modules/this/code/poetry.lock
│ > cd /var/folders/4b/sgc_nhbs6s3frndkq1c_nqwm0000gp/T/terraform-aws-lambda-p8sv_58c
│ > ['poetry config --no-interaction virtualenvs.create true', 'poetry config --no-interaction virtualenvs.in-project true', 'poetry export --format requirements.txt --output
│ requirements.txt --with-credentials', 'python3.9 -m pip install --no-compile --no-deps --prefix= --target=. --requirement=requirements.txt']
│ zip: Error during zip archive creation
│ Traceback (most recent call last):
│   File "/code/project/dev/us-west-2/.terraform/modules/this.lambda/package.py", line 1520, in build_command
│     bpm.execute(build_plan, zs, query)
│   File "/code/project/dev/us-west-2/.terraform/modules/this.lambda/package.py", line 868, in execute
│     with install_poetry_dependencies(query, path) as rd:
│   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
│     return next(self.gen)
│   File "/code/project/dev/us-west-2/.terraform/modules/this.lambda/package.py", line 1187, in install_poetry_dependencies
│     check_call(poetry_command, env=subproc_env)
│   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 368, in check_call
│     retcode = call(*popenargs, **kwargs)
│   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 349, in call
│     with Popen(*popenargs, **kwargs) as p:
│   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
│     self._execute_child(args, executable, preexec_fn, close_fds,
│   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
│     raise child_exception_type(errno_num, err_msg, err_filename)
│ FileNotFoundError: [Errno 2] No such file or directory: 'poetry config --no-interaction virtualenvs.create true'
│ 
```

**Comment by pdecat** [comment]
Hi @aminclip, are you using the `build_in_docker` parameter? If so, which value do you pass in it?

Given the actual error you are seeing, `No such file or directory: 'poetry config --no-interaction virtualenvs.create true'`, I believe there's a code path where the command parts are concatenated but they should not.

Also, please note that the environment (local env or docker image) where the configuration is [must provide the `poetry` command](https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/311/files#diff-34b2a63c4b18a635042766329eca28d8801699eecf5e93eaedaeda1309931381R1109). I just realized this isn't mentioned in the README.

**Comment by aminclip** [comment]
Hi @pdecat , I'm not using `build_in_docker` or anything related to the Docker ecosystem.

**Comment by pdecat** [comment]
Hi @aminclip, I've reproduced the issue when not using docker to build packages with poetry. Working on a fix...

**Comment by pdecat** [comment]
Submitted #420 to fix the issue.

**Comment by antonbabenko** [comment]
@pdecat Thanks a lot for a quick fix!

@aminclip Could you please try the fix and confirm that it works for you before we merge it?

**Comment by aminclip** [comment]
Hi @pdecat and @antonbabenko, I reviewed and tested. everything works as expected. I think we can merge.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.10.1 :tada:
