### ISSUE TITLE
Lambda packaging suddenly failing.

### ISSUE THREAD

**Issue by spliskamatyshak-w3** [terraform-aws-modules/terraform-aws-lambda#430]
## Description

I can't honestly explain what is going on because it worked Friday and today it doesn't. I see no significant changes to anything related to this code. Already tried backing out to aws provider 4.56.0. Same exact messages.
```
│ Error: External Program Execution Failed
│ 
│   with module.edge_lambda.data.external.archive_prepare[0],
│   on .terraform/modules/edge_lambda/package.tf line 10, in data "external" "archive_prepare":
│   10:   program = [local.python, "${path.module}/package.py", "prepare"]
│ 
│ The data source received an unexpected error while attempting to execute the program.
│ 
│ Program: /usr/local/bin/python3
│ Error Message: Traceback (most recent call last):
│   File "/Users/spliskamatyshak/Documents/GitHub/discover-api/infrastructure/pipelines/acct-infra/.terraform/modules/edge_lambda/package.py", line 1627, in <module>
│     main()
│   File "/Users/spliskamatyshak/Documents/GitHub/discover-api/infrastructure/pipelines/acct-infra/.terraform/modules/edge_lambda/package.py", line 1623, in main
│     exit(args.command(args))
│          ^^^^^^^^^^^^^^^^^^
│   File "/Users/spliskamatyshak/Documents/GitHub/discover-api/infrastructure/pipelines/acct-infra/.terraform/modules/edge_lambda/package.py", line 1433, in prepare_command
│     content_hash.update(hash_extra.encode())
│                         ^^^^^^^^^^^^^^^^^
│ AttributeError: 'NoneType' object has no attribute 'encode'
│ 
│ State: exit status 1
```

If your request is for a new feature, please use the `Feature request` template.

- [*] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
4.10.1
- Terraform version:

1.3.9
- Provider version(s):

+ provider registry.terraform.io/hashicorp/aws v4.57.0
+ provider registry.terraform.io/hashicorp/external v2.3.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
## Reproduction Code [Required]

```
module "edge_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 4.10"

  function_name  = "within3-discover-headers"
  description    = "Edge lambda for auth0"
  handler        = "index.header"
  runtime        = "nodejs16.x"
  lambda_at_edge = true
  source_path    = "${path.root}/../../fixtures/edge"
}
```

## Expected behavior

Should package the lambda as it has until today.

## Actual behavior

See error above.

**Comment by kunalmbm** [comment]
I am also facing this issue for our prod deployment on version 1.38.0.
Did anyone found the root cause or fix for this issue?

**Comment by pneigel-ca** [comment]
It appears this could be related to the external provider used for the data source.

Link to relevant issue and discussion: https://github.com/hashicorp/terraform-provider-external/issues/193

**Comment by drewclardy** [comment]
Setting the `hash_extra` input to an arbitrary value got around this issue.

**Comment by pneigel-ca** [comment]
Updating to `v2.3.1` of the external provider fixed the issue for my team.

If you are obtaining the latest provider/not setting constraints, the next deployment should detect this from registry.

**Comment by spliskamatyshak-w3** [comment]
I ended up blowing away my repo locally and recloning before things started working again. I'm guessing ultimately, it was the external provider update that actually fixed this.
