### ISSUE TITLE
FileNotFoundError: plan.json file not found on Terraform Apply from CI/CD

### ISSUE THREAD

**Issue by lsanchez-v** [terraform-aws-modules/terraform-aws-lambda#635]
## Description

Hi,

I'm trying to create a lambda function using the code below, but although it works running terraform from local, it **sometimes** fails at the Azure Devops pipeline I'm trying to deploy it from:

```
│ Error: local-exec provisioner error
│ 
│   with module.lambda.module.investigate_input_data_classifier.module.investigate_input_data_classifier.null_resource.archive[0],
│   on .terraform/modules/lambda.investigate_input_data_classifier.investigate_input_data_classifier/package.tf line 67, in resource "null_resource" "archive":
│   67:   provisioner "local-exec" {
│ 
│ Error running command
│ 'builds/d8a7d0ff47c46647723b805083cd5b654e36c33856c22de43fa64122ebb3f470.plan.json':
│ exit status 1. Output: CMD: python3
│ .terraform/modules/lambda.investigate_input_data_classifier.investigate_input_data_classifier/package.py
│ build --timestamp 1730213269269287200
│ builds/d8a7d0ff47c46647723b805083cd5b654e36c33856c22de43fa64122ebb3f470.plan.json
│ Traceback (most recent call last):
│   File "/root/myagent/_work/5/s/terraform/.terraform/modules/lambda.investigate_input_data_classifier.investigate_input_data_classifier/package.py", line 1800, in <module>
│     main()
│   File "/root/myagent/_work/5/s/terraform/.terraform/modules/lambda.investigate_input_data_classifier.investigate_input_data_classifier/package.py", line 1796, in main
│     exit(args.command(args))
│          ^^^^^^^^^^^^^^^^^^
│   File "/root/myagent/_work/5/s/terraform/.terraform/modules/lambda.investigate_input_data_classifier.investigate_input_data_classifier/package.py", line 1639, in build_command
│     with open(args.build_plan_file) as f:
│          ^^^^^^^^^^^^^^^^^^^^^^^^^^
│ FileNotFoundError: [Errno 2] No such file or directory:
│ 'builds/d8a7d0ff47c46647723b805083cd5b654e36c33856c22de43fa64122ebb3f470.plan.json'

``` 
The really weird thing is that it sometimes work, and sometimes it fails, and I haven't been able to identify what makes it failing or not.

## Versions

- Module version [Required]: 7.14.0

- Terraform version: 1.9.8

- Provider version(s): 5.73.0

## Reproduction Code [Required]

```hcl
module "investigate_input_data_classifier" {
  source        = "terraform-aws-modules/lambda/aws"
  version       = "v7.14.0"

  timeout       = 900
  function_name = var.lambda_function_name
  handler       = "${var.lambda_function_name}.lambda_handler"
  runtime       = var.python_runtime_version
  publish       = true

  source_path = "${path.module}/src"

  cloudwatch_logs_retention_in_days = 7

  memory_size            = 10240
  ephemeral_storage_size = 10240

  store_on_s3 = true
  s3_bucket   = var.lambda_source_bucket_id
  s3_prefix   = "${var.lambda_function_name}/"

  vpc_security_group_ids = [
    aws_security_group.investigate_input_data_classifier_sg.id
  ]
  vpc_subnet_ids = var.vpc_private_subnets_ids

  create_role                   = true
  attach_cloudwatch_logs_policy = true
  attach_network_policy         = true

  attach_policies = true
  policies = [
    aws_iam_policy.investigate_input_data_classifier_s3.arn,
    data.aws_iam_policy.aws_lambda_basic_execution_role.arn
  ]
  number_of_policies = 2

  allowed_triggers = {
    TriggerLambdaOnNewS3Object = {
      statement_id = "AllowS3Invoke"
      principal    = "s3.amazonaws.com"
      source_arn   = var.investigate_data_bucket_arn
    }
  }

  environment_variables = {
    "SNS_TOPIC_ARN" = var.lambda_errors_sns_topic_arn
  }

  function_tags = var.tags
}
``` 

Run `terraform apply`

## Expected behavior

The lambda function is deployed successfully

## Actual behavior

It's failing from CI/CD with the error mentioned above.

### Terminal Output Screenshot(s)

![image](https://github.com/user-attachments/assets/a428e36f-abaa-4476-9d27-c077640e467b)

**Comment by Dizotoff** [comment]
Experience the same with AWS
